version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: t10-challenge-api:dev
    container_name: t10-challenge-api
    command: sleep infinity
    volumes:
      - .:/home/vscode/api
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    container_name: t10-challenge-db
    tty: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=t10_challenge
    volumes:
      - ./.pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: t10-challenge-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=123
    volumes:
      - ./.pgadmin:/var/lib/pgadmin
    ports:
      - 9009:80
