FROM golang:1.14.7-alpine AS builder

ENV GO111MODULE=on

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -ldflags="-w -s" -o main cmd/rest/main.go

FROM alpine:latest

COPY --from=builder /app/main /main

EXPOSE 80

ENTRYPOINT [ "/main" ]
